import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  //const route = useRoute();
  return (
    <html lang='en'>
      <body>
        {/*}{route == "signin" || route == "signup" ? <div>Header</div>}*/}
        {children}
        {/*{route == "signup" || route == "signup" ? <div>Footer</div>}*/}
      </body>
    </html>
  );
}
